openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of contact app
tags:
  - name: Contacts
    description: Operation about users.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-xwtz.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
