openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of contact app
tags:
  - name: Contacts
    description: Operation about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  # /contacts:
  #   get:
  #     $ref: ../swagger/paths/contacts/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
